version: 2.1
jobs:
  vm_test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: python3 -m pip install --upgrade pip
      - run: python3 -m pip install --upgrade certifi 
      - run: pip3 install -r requirements
      - run: pytest -vs
  docker_test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: docker build --tag=test .
      - run: docker-compose up

workflows:
  build_and_test:
    jobs:
      - vm_test
      - docker_test
