version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02 
    steps:
      - run: lsb_release -a
      - run: ls
      - run: docker version
      - run: python3 --version
workflows:
  build_and_test:
    jobs:
      - build
