version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    working_directory: ./email_routine_python
    steps:
      - checkout
      - run:
        name: check enviroment
        command: echo $AUTH_STRING
      - run:
        name: install dependencies
        command: pip install -r requirements
      - run:
        name: sending test email
        command: python email_routine.py
  test:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - run:
        name: tests
        command: pytest
workflows:
  build_and_test:
    jobs:
      - build
