version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - run: echo $AUTH_STRING
      - run: pip install -r requirements
      - run: python email_routine.py
workflows:
  build_and_test:
    jobs:
      - build
